services:
  revance-test.rigoli.dev:
    container_name: revance-test.rigoli.dev
    image: revance-test.rigoli.dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PROXY_VIRTUAL_PORT}
    environment:
      VIRTUAL_HOST: ${PROXY_VIRTUAL_HOST}
      VIRTUAL_PORT: ${PROXY_VIRTUAL_PORT}
networks:
  default:
    external: true
    name: proxy
